# Generated by Django 4.2.2 on 2025-01-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailingRecipient",
            new_name="Recipient",
        ),
    ]
