# Generated by Django 4.2.2 on 2025-01-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_rename_mailingrecipient_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtemptSending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_atempt", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(verbose_name="статус рассылки")),
                (
                    "server_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "sending",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending",
                        to="mail.sending",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["-date_atempt"],
            },
        ),
    ]
