# Generated by Django 4.2.2 on 2025-01-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_message_options_alter_recipient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="sending",
            name="created_by",
        ),
    ]
